development:
  adapter: postgresql
  database: exam1_production
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: exam1_production
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: exam1_production
  username: exam1
  password: <%= ENV['EXAM1_DATABASE_PASSWORD'] %>
